// Copyright 2020 The Terasology Foundation
// SPDX-License-Identifier: Apache-2.0
package org.terasology.scenario.internal.events;

import org.terasology.engine.entitySystem.entity.EntityRef;
import org.terasology.engine.entitySystem.event.Event;
import org.terasology.scenario.internal.systems.ConvertIntoEntitySystem;

import java.util.List;

/**
 * Event that for converting a list of serialised strings(generated by ConvertEntitySystem) back into an entity Using
 * {@link ConvertIntoEntitySystem}
 */
public class ConvertIntoEntityEvent implements Event {
    private List<String> constructionStrings;
    private EntityRef returnEntity;

    public ConvertIntoEntityEvent() {
    }

    public ConvertIntoEntityEvent(List<String> constructionStrings) {
        this.constructionStrings = constructionStrings;
    }

    public List<String> getConstructionStrings() {
        return constructionStrings;
    }

    public EntityRef getReturnEntity() {
        return returnEntity;
    }

    public void setReturnEntity(EntityRef returnEntity) {
        this.returnEntity = returnEntity;
    }
}
