/*
 * Copyright 2017 MovingBlocks
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.terasology.scenario.internal.events;

import org.terasology.entitySystem.entity.EntityRef;
import org.terasology.entitySystem.event.Event;

import java.util.List;

/**
 * Event that for converting a list of serialised strings(generated by ConvertEntitySystem) back into an entity
 * Using ConvertIntoEntitySystem
 */
public class ConvertIntoEntityEvent implements Event {
    private List<String> constructionStrings;
    private EntityRef returnEntity;

    public ConvertIntoEntityEvent() {}

    public ConvertIntoEntityEvent(List<String> constructionStrings) {
        this.constructionStrings = constructionStrings;
    }

    public List<String> getConstructionStrings() {
        return constructionStrings;
    }

    public EntityRef getReturnEntity() {
        return returnEntity;
    }

    public void setReturnEntity(EntityRef returnEntity) {
        this.returnEntity = returnEntity;
    }
}
