// Copyright 2020 The Terasology Foundation
// SPDX-License-Identifier: Apache-2.0
package org.terasology.scenario.internal.events;

import org.terasology.engine.entitySystem.event.Event;
import org.terasology.scenario.internal.systems.ConvertIntoEntitySystem;

/**
 * Event that for converting a single serialised string(generated by ConvertEntitySystem) back into an entity. This
 * entity is always a scenario constant value'd entity Using {@link ConvertIntoEntitySystem}
 */
public class ConvertIntoEntityConstantEvent implements Event {
    private String value;

    public ConvertIntoEntityConstantEvent() {
    }

    public ConvertIntoEntityConstantEvent(String value) {
        this.value = value;
    }

    public String getValue() {
        return value;
    }
}
