// Copyright 2020 The Terasology Foundation
// SPDX-License-Identifier: Apache-2.0
package org.terasology.scenario.internal.events;

import org.terasology.engine.entitySystem.entity.EntityRef;
import org.terasology.engine.entitySystem.event.Event;
import org.terasology.engine.network.ServerEvent;
import org.terasology.scenario.internal.systems.ConvertEntitySystem;
import org.terasology.scenario.internal.systems.ConvertIntoEntitySystem;

import java.util.List;

/**
 * Event that is called that tells the server to recreate the entity on the server side based on a list of serialized
 * strings generated by the client by the logic editing screen
 * <p>
 * Construction strings are created from an entity by using {@link ConvertEntitySystem} Construction strings are used to
 * create an entity by using {@link ConvertIntoEntitySystem}
 */
@ServerEvent
public class ReplaceEntityFromConstructionStringsEvent implements Event {
    private EntityRef replaceEntity;
    private List<String> conversions;

    public ReplaceEntityFromConstructionStringsEvent() {
    }

    public ReplaceEntityFromConstructionStringsEvent(EntityRef replaceEntity, List<String> conversions) {
        this.replaceEntity = replaceEntity;
        this.conversions = conversions;
    }

    public EntityRef getReplaced() {
        return replaceEntity;
    }

    public List<String> getConversions() {
        return conversions;
    }
}
